### ISSUE TITLE
MacOS - ModuleNotFoundError: No module named 'distutils

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-datta-able-pro#13]
> Reported in support (Discord)

```log
ModuleNotFoundError: No module named 'distutils
``` 

Patch:  replace `strtobool` with `str2bool`

To be taken into account.

**Comment by ghost** [comment]
Install `setuptools` will solve the problem.

`pip install setuptools`.

I have added it in the `requirements.txt` file also

**Comment by app-generator** [comment]
Closing.
