### ISSUE TITLE
A file is missing on Django Datta Able PRO

### ISSUE THREAD

**Issue by jorgeassuncao** [app-generator/django-datta-able-pro#2]
Hi, the file `index-chart-package.html` is missing from Django Datta Able PRO.

![image](https://github.com/app-generator/django-datta-able-pro/assets/7755388/65ef77d8-6950-4581-8ab4-016edcaa3206)

![image](https://github.com/app-generator/django-datta-able-pro/assets/7755388/44ac7fe5-4e85-41bd-9f40-9471cba8874a)

**Comment by app-generator** [comment]
Hello @jorgeassuncao 

The issue is visible in the `ENH` version. We've released a new version & uploaded it on GUMROAD. 

In case you want direct access to the REPO, let us know. 

We can add you to the repo.
