### ISSUE TITLE
Python version is not being changed to the value in Dockerfile

### ISSUE THREAD

**Issue by jorgeassuncao** [app-generator/django-datta-able-pro#5]
I'm using Django Datta Able Pro and deploying with Docker. Tried to change the version of Python that is used on the image and changed a line in the Dockerfile file from `FROM python:3.9`  to `FROM python:3.11`. When building, i see this in the log:

```
 => [internal] load metadata for docker.io/library/p
 => [1/6] FROM docker.io/library/python:3.9@sha256:b
 => => resolve docker.io/library/python:3.9@sha256:b
```

I've also tried changing into this:
```
FROM debian:bullseye-slim

# Install Python 3.11 and other dependencies
RUN apt-get update && apt-get install -y python3.11 && apt-get clean
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
```

but the log says the same thing. Looks like the Dockerfile is completely ignored.

**Comment by app-generator** [comment]
Closing.
