### ISSUE TITLE
ModuleNotFoundError: No module named 'MySQLdb'

### ISSUE THREAD

**Issue by dasvaders** [app-generator/django-datta-able-pro#6]
Hello, first of all sorry for my bad English, I'm not a native English speaker.
I've got an error message while I was trying to 

$ docker-compose up --build 

here's the step what I've done.

● Product: django-datta-able-pro
● Developing environ: Oracle Cloud freetier Ubuntu 22.04
   separate 2 instance for use
       1. web             152.70.111.111
       2. mysql-db     152.70.222.222

■ **What I've done**

> **STEP 1.** 
-  Download product file from appseed.us

> **STEP 2.** 
-  Upload source code to github private repo

> **STEP 3.** 
- Clonning source datas from github using 'git clone <https:repo>'

> **STEP 4.** 
- Install python3.9 following installation document
- https://docs.appseed.us/content/how-to/install-python38-ubuntu
- Install up to date mysqlclient

> **STEP 5.** 
- Did docker-compose up --build for test
- opened Oracle Cloud Ports in the first instance and iptables as well
everything was successfully worked.
I was able to connect the web page as well without any problems

> **STEP 6.** 
- for further test, I did manual build for ubuntu.
- following steps suggestion of appseed documentation.
- https://docs.appseed.us/products/django-dashboards/datta-able-pro

      $ virtualenv env
      $ source env/bin/activate
      $ pip3 install -r requirements.txt
      $ python manage.py makemigrations
      $ python manage.py migrate
      $ python manage.py runserver 0.0.0.0:80

It worked very well.

> **STEP 7.** 
- After that I wanted switch default db to mysql. So I added some code following steps by
- https://docs.appseed.us/content/how-to/use-mysql-with-django
     
.env
---------------------------------------------------------
       DB_ENGINE=mysql
       DB_NAME=appseed_db
       DB_HOST=152.70.222.222
       DB_PORT=3306
       DB_USERNAME=appseed_db_user
       DB_PASS=dbpass

core.settings.py
----------------------------------------------------------
        'ENGINE'  : 'django.db.backends.mysql', 
        'NAME'    : os.getenv('DB_NAME'     , 'appseed_db'),
        'USER'    : os.getenv('DB_USERNAME' , 'appseed_db_user'),
        'PASSWORD': os.getenv('DB_PASS'     , 'dbpass'),
        'HOST'    : os.getenv('DB_HOST'     , '152.70.222.222'),
        'PORT'    : os.getenv('DB_PORT'     , 3306),

and I made db_name, db_user_name, in MYSQL DB SERVER (152.70.222.222)

       mysql> create DATABASE appseed_db;
       Query OK, 0 rows affected (0.00 sec)

       mysql> create user 'appseed_db_user'@'%' identified by 'dbpass';
       Query OK, 0 rows affected (0.00 sec)

       mysql> grant all privileges on `appseed_db` . * to 'appseed_db_user'@'%';
       Query OK, 0 rows affected (0.00 sec)

       mysql> flush privileges;
       Query OK, 0 rows affected (0.00 sec)

After that I did connetion test from Windows MySql Workbench successfully.

> **STEP 8.** 
- update the source I edited using 'git pull' in web server(152.70.111.111)
- Did manual build again(what I've done in STEP 6.)
- Database tables updated when I migrate the data
![image](https://user-images.githubusercontent.com/107455442/182204063-331fed4c-2382-432d-9f13-8e844c27af9a.png)

`$ python manage.py runserver 0.0.0.0:80`
everything was working very well

> **STEP 9.** 
- Problems had happened from this step
- I did STEP 5. again for test
- I saw an error message in env prompt as well as without env
-------------------------------------------------------------------------
- ***Also saw the same messages on Windows environment***
- https://docs.appseed.us/content/how-to/install-docker-on-windows
- above page shows how to install windows docker and how to use it
-------------------------------------------------------------------------

`docker-compose up --build`

       Building appseed-app
       Sending build context to Docker daemon  173.4MB
       Step 1/9 : FROM python:3.9
        ---> b673851840e8
       Step 2/9 : ENV PYTHONDONTWRITEBYTECODE 1
        ---> Using cache
        ---> 14e56f79d31d
       Step 3/9 : ENV PYTHONUNBUFFERED 1
        ---> Using cache
        ---> b5133b3ecbac
       Step 4/9 : COPY requirements.txt .
        ---> Using cache
        ---> 39df4d7aa020
       Step 5/9 : RUN pip install --upgrade pip
        ---> Using cache
        ---> 6124a22d34e9
       Step 6/9 : RUN pip install --no-cache-dir -r requirements.txt
        ---> Using cache
        ---> dfdb97b2de61
       Step 7/9 : COPY . .
        ---> Using cache
        ---> 1912e7a1afc6
       Step 8/9 : RUN python manage.py migrate
        ---> Running in ab336749ddcf
       Traceback (most recent call last):
       File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 15, in <module>
       import MySQLdb as Database
       ModuleNotFoundError: No module named 'MySQLdb'

       The above exception was the direct cause of the following exception:

       Traceback (most recent call last):
         File "//manage.py", line 22, in <module>
           main()
         File "//manage.py", line 19, in main
           execute_from_command_line(sys.argv)
         File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
           utility.execute()
         File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
           django.setup()
         File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
           apps.populate(settings.INSTALLED_APPS)
         File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 114, in populate
           app_config.import_models()
         File "/usr/local/lib/python3.9/site-packages/django/apps/config.py", line 301, in import_models
           self.models_module = import_module(models_module_name)
         File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
         File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 850, in exec_module
         File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
         File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/models.py", line 3, in <module>
           from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
         File "/usr/local/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 48, in <module>
           class AbstractBaseUser(models.Model):
         File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 122, in __new__
           new_class.add_to_class('_meta', Options(meta, app_label))
         File "/usr/local/lib/python3.9/site-packages/django/db/models/base.py", line 326, in add_to_class
           value.contribute_to_class(cls, name)
         File "/usr/local/lib/python3.9/site-packages/django/db/models/options.py", line 207, in contribute_to_class
           self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
         File "/usr/local/lib/python3.9/site-packages/django/utils/connection.py", line 15, in __getattr__
           return getattr(self._connections[self._alias], item)
         File "/usr/local/lib/python3.9/site-packages/django/utils/connection.py", line 62, in __getitem__
           conn = self.create_connection(alias)
         File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 204, in create_connection
           backend = load_backend(db['ENGINE'])
         File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 111, in load_backend
           return import_module('%s.base' % backend_name)
         File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py", line 17, in <module>
           raise ImproperlyConfigured(
       django.core.exceptions.ImproperlyConfigured: Error loading MySQLdb module.
       Did you install mysqlclient?

> **STEP 9.** 
- I'd track back where the python installed and what is in
` "/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/` is

       # whereis python3.9
       python3.9: /usr/bin/python3.9 /usr/lib/python3.9 /etc/python3.9 /usr/local/lib/python3.9 /usr/share/man/man1/python3.9.1.gz

       # python -V
       Python 3.10.4

       # cd /usr/bin/python3.9
       # -bash: cd: /usr/bin/python3.9: Not a directory

       # cd /usr/lib/python3.9
       /usr/lib/python3.9# ls
 
![image](https://user-images.githubusercontent.com/107455442/182207598-d72bf4dc-b2bb-4bf9-ab4d-84554b844f89.png)
definitely not have any 'site-packages' folder

       # cd /etc/python3.9
       sitecustomize.py

       # cd /usr/local/lib/python3.9
       /usr/local/lib/python3.9# ls
       dist-packages
       /usr/local/lib/python3.9# cd dist-packages/
       /usr/local/lib/python3.9/dist-packages# ls
      empty

I couldn't find python/site-packages from anywhere and even more my default python version is now 3.10.4

> **STEP 10.** 
- So, I installed python 3.9 again and get in the directory where error messages shown me
- there was only 'dist-packages' folder
- I've changed default python version 3.9 and `docker-compose up --build` again but had same messages
- After that I was wondering that why there was no problem when I did STEP 6. and where the hell
- `/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py` is
- after I found that the base.py is in my 
- `/usr/local/lib/python3.10/dist-packages/django/db/backends/base` folder
- but whatever I tried change default python version, whenever using env mode or not it referrenced the same directory
- `/usr/local/lib/python3.9/site-packages/django/db/backends/mysql/base.py`

What did I do wrong? I don't know what should I do. 
I'm wresting with this problem for 2 days
Please help me about this.

Ps. I bought a domain and I want to use it on docker but I don't know how to the port forward (ngnix 5085) in appseed-app.conf at all
here's what I modified 

appseed-app.conf
------------------------------------------------------------------------------------
      upstream webapp {
          server appseed_app:5005;
      }

     server {
         listen 5085;
         #listen 80;
         #server_name localhost;
         server_name abc.net;

    location / {
        proxy_pass http://webapp;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }}

ex) let's say I have abc.com:
if I connect abc.com, there was no response 
but when I connect abc.com:5085, it worked

how can I solve this?

PS 2. To be honest I don't need Docker at all. because my project is so small so I only need python/mysql/django/wsgi/nginx but because I don't know how to modify the source right now I don't have any choice but use dedicated Docker.

**Comment by app-generator** [comment]
The most simple way to use the starter with MySql is to follow up these steps: 

**Note:** Make sure your Mysql server is properly installed and accessible. 

> **Step 1** - Create the MySql Database to be used by the app

- `Create a new MySql` database
- `Create a new user` and assign full privileges (read/write)

<br />

> **Step 2** - Edit the `.env` to match your MySql DB credentials. Make sure `DB_ENGINE` is set to `mysql`.

- `DB_ENGINE`  : `mysql` 
- `DB_NAME`    : default value = `appseed_db`
- `DB_HOST`    : default value = `localhost`
- `DB_PORT`    : default value = `3306`
- `DB_USERNAME`: default value = `appseed_db_usr`
- `DB_PASS`    : default value = `pass`

<br />

Here is a sample:  

```txt
# .env sample

DB_ENGINE=mysql             # Database Driver
DB_NAME=appseed_db          # Database Name
DB_USERNAME=appseed_db_usr  # Database User
DB_PASS=STRONG_PASS_HERE    # Password 
DB_HOST=localhost           # Database HOST, default is localhost 
DB_PORT=3306                # MySql port, default = 3306 
```

<br />

From this point, the usual Django set up should be followed. 

```bash
$ virtualenv env
$ source env/bin/activate
$ pip3 install -r requirements.txt
$
$ python manage.py makemigrations
$ python manage.py migrate
$ 
$ python manage.py runserver
```

Let us know if you had issues.

**Comment by dasvaders** [comment]
The way you mentioned is the method I've already done.
and I've mentioned your instruction url many times because I thought you think that I'm not take a look at the instructions that you provided.

What I was going to ask about the product is why it keeps referenced 
`/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py` folder

I think the reason why `ModuleNotFoundError: No module named 'MySQLdb'` error has occured in my issue is
it cannot find profer folder during migration. 

despite I've changed default python version several times and sevaral ways it just keeps designate the same folder
`/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py`  which does exist.

**Comment by app-generator** [comment]
Hello @dasvaders 

Did you succeed to manage it?

**Comment by dasvaders** [comment]
yes somehow I could manage what I've asked
