### ISSUE TITLE
Morris bar chart width invalid 

### ISSUE THREAD

**Issue by andr0s** [app-generator/django-datta-able-pro#7]
Chrome Version 104.0.5112.101 (Official Build) (arm64) Mac OS

When I have a Morris bar chart, sometimes the widths of the inner SVG and the RECTs are invalid. This results in the bar being too wide. After refreshing the same page, the problem disappears. My guess is that it relates somehow to the "sliding" that the page content does (for some reasons) during load. It kinda slides from left to right, like it expands from the right menu. But that might not be the case. I can try to disable that "slide" if you tell me how, and will let you know if that helped.

I'm not good at JS and I have no idea how to fix that honestly.

This one is broken:

<img width="1255" alt="Screen Shot 2022-08-27 at 17 44 33" src="https://user-images.githubusercontent.com/298775/187027010-1465c435-938c-40e5-a42a-72c80434c0b1.png">

This one is good:

<img width="1280" alt="Screen Shot 2022-08-27 at 17 45 00" src="https://user-images.githubusercontent.com/298775/187026998-5d4bedd5-75aa-4295-9cfa-28ad5790af0c.png">

These are screenshots of the same page.

The chart is initialized by this code:

```
        $(Morris.Bar({
          element: 'morris-area-curved-chart',
          data: [
            {% for ts in ts_data %}
                { y: '{{ ts.0 }}', a: {{ ts.1 }} }   {% if not forloop.last %},{% endif%}
            {% endfor %}
          ],
          xkey: 'y',
          ykeys: ['a' ],
          labels: [''],
          barColors: function (row, series, type) {
            if (row.y < 0) return '#990000';
            return '#55CC55';
          },
        }));
```

**Comment by app-generator** [comment]
Hello @andr0s,

This issue is visible in the version we provide or in your custom code?

If is in our version, please mention the page in order to take a look. 

Ty

**Comment by andr0s** [comment]
@app-generator no, that's a custom code, unfortunately. Never seen that on your chart page. My guess is that it happens when there are a lot of bars in the graph. But still I consider this to be a bug because it does resize properly - and looks good - after refreshing the page

**Comment by andr0s** [comment]
Update - the issue doesn't seem to be depending on the amount of data. Even relatively small numbers of bars still break the layout sometimes

<img width="997" alt="Screen Shot 2022-08-30 at 13 58 37" src="https://user-images.githubusercontent.com/298775/187371003-ea29cedd-b9ac-4bbd-a5c6-8c8055112240.png">

**Comment by app-generator** [comment]
Hello @andr0s, 

I suspect is a timing issue. 

How the data is pulled into charts?
Via an API, loaded from the controller?

**Comment by andr0s** [comment]
The data is just written in the source code of the page. 
pls see my first message, it’s basically 
data: [
            {% for ts in ts_data %}
                { y: '{{ ts.0 }}', a: {{ ts.1 }} }   {% if not forloop.last %},{% endif%}
            {% endfor %}
          ],

**Comment by andr0s** [comment]
I fixed it. Just like I thought, it was because of the animation. The main content block had "transition" in CSS and the chart was taking the wrong width when it was drawing itself, that width then narrowed down due to animation. So I just disabled those transition effects in CSS and now things work just fine

**Comment by app-generator** [comment]
🚀🚀
