### ISSUE TITLE
loader-track

### ISSUE THREAD

**Issue by Eric-Simon-Lemon** [app-generator/django-datta-able-pro#7]
Hi ! 
I have some troubles with the loader-track at the top of the pages :

- Started a new django project and installed the template package the same way it's done here
git+https://${GITHUB_TOKEN}@github.com/app-generator/priv-django-admin-datta-pro

- I then included the package urls in my project urls :
path("", include('admin_datta_pro.urls'))
--> everything works as intended

- Then, for future customisation purpose I got all the statics from the package into my project statics folder
--> still works

- I copied the minimum templates into my app : base.html and every includes, made a new index view with a demo index template, changed the menu list to only have my first index page in it and made sure the url would match
--> it works, I can see my page and the included sidebar, header, ... around.

- then I wanted to strip down the parts I had no use for : in navigation.html, I removed the search input field 
--> reloaded my page : the loader-track component at the top (rainbow going from left to right) won't stop now !
tried with removing other parts in the same file, still the same result
replaced the content with the original navigation.html content : loader-track works again.

How Am I supposed to make that component work properly even with some changes in the included html files ?

Note : It only happened with navigation.html so far, but I can't say if other files would trigger the same problem. 
My web dev skill level being what it is, it's a bit hard for me to track what's happening !

Thank you for you help, and have a nice day !

**Comment by app-generator** [comment]
Noted @Eric-Simon-Lemon 

A developer will take a look.

TY!

**Comment by Eric-Simon-Lemon** [comment]
Same thing happens if I remove the whole navigation include in my base.html
![image](https://github.com/app-generator/django-datta-able-pro/assets/150436283/9895a8cb-a05c-423c-8f82-3d0dd37325dc)

![image](https://github.com/app-generator/django-datta-able-pro/assets/150436283/ef2390eb-d69a-49bc-9133-a6a2080a73b8)

**Comment by ghost** [comment]
Hello @Eric-Simon-Lemon,

If you inspect the console in your browser then you will notice the error.

In your case, there are two css class in the navigation form input field that are used in javascript `search-btn` and `search-close`. But when you remove the search input field from the navigation then those two css classes are not found by javascript and thrown an error. That's why the loader is keep moving.

Solution:
- When you remove any of the html tag or block you have to remove the corresponding css class or id from the javascript also.


Thank you

**Comment by Eric-Simon-Lemon** [comment]
Yes found it (in static/assets/js/pcoded.js for those wondering)
Thank you and have a nice day !
