### ISSUE TITLE
[Email Support] Prevent sidebar collapse in small devices

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-datta-able-pro#8]
The client requests how to prevent sidebar collapse on small devices:

> To be investigated. 

![image](https://github.com/app-generator/django-datta-able-pro/assets/51070104/256a1dbf-9fc3-42b5-9a1b-d726cf25a6f2)

**Comment by elcomandante** [comment]
> The client requests how to prevent sidebar collapse on small devices:

The problem is on large screens. I think is fine for the sidebar to collapse on a mobile phone.

**Comment by app-generator** [comment]
Closing.
